### ISSUE TITLE
token_v2_processor panics on version 2819452713 due to missing metadata

### ISSUE THREAD

**Issue by ruslan-y** [aptos-labs/aptos-indexer-processors-v2#117]
### Summary

The `token_v2_processor` crashes with a panic when processing version `2819452713`. The cause appears to be a missing metadata entry for a token claim.

### Log error
```
{
  "timestamp": "2025-06-04T21:43:49.341290Z",
  "level": "ERROR",
  "message": "details = \"\"\"\npanicked at processor/src/processors/token_v2/token_models/token_claims.rs:180:17:\nMissing table handle metadata for claim. Version: 2819452713, table handle for PendingClaims: 0x5459a6e0aae6906091deae5325a75b46b08d146dfa95c5b7e628f9bbef34b2db, all metadata: {} Missing token data id in token claim event. token_data_id: 0xb2cb896f1de65e175f99f58111adb037f2a7f40a2dba4d25da38d90a5ed55e99, all token claim events: {}\"\"\"\nbacktrace = \"\"\"\n   0:     0x55ca7bd70e40 - aptos_indexer_processor_sdk::server_framework::setup_panic_handler::{{closure}}::hf5cd9c630cc4f8eb\n   1:     0x55ca7c4d9273 - std::panicking::rust_panic_with_hook::ha9131beeb2ddc506\n   2:     0x55ca7c4d8f4a - std::panicking::begin_panic_handler::{{closure}}::h1bba0eaeb6da506f\n   3:     0x55ca7c4d7ef9 - std::sys::backtrace::__rust_end_short_backtrace::h1d1ca3eade483f4c\n   4:     0x55ca7c4d8bdd - rust_begin_unwind\n   5:     0x55ca7b09ff40 - core::panicking::panic_fmt::h896a0727a1a943f9\n   6:     0x55ca7b26aca1 - processor::processors::token_v2::token_models::token_claims::CurrentTokenPendingClaim::from_delete_table_item::h670a4cccd9f87614\n   7:     0x55ca7b27a45b - processor::processors::token_v2::token_v2_processor_helpers::parse_v2_token::{{closure}}::h906d1826c8dd8c4d\n   8:     0x55ca7b2aed7a - <processor::processors::token_v2::token_v2_extractor::TokenV2Extractor as aptos_indexer_processor_sdk::traits::processable::Processable>::process::{{closure}}::hf738a2cac5ec14a0\n   9:     0x55ca7b94e8f8 - <aptos_indexer_processor_sdk::traits::async_step::RunnableAsyncStep<Step> as aptos_indexer_processor_sdk::traits::runnable_step::RunnableStep<<Step as aptos_indexer_processor_sdk::traits::processable::Processable>::Input,<Step as aptos_indexer_processor_sdk::traits::processable::Processable>::Output>>::spawn::{{closure}}::h765f2fb663c98b37\n  10:     0x55ca7ba19877 - tokio::runtime::task::core::Core<T,S>::poll::hf07e0759022baf50\n  11:     0x55ca7b87064b - tokio::runtime::task::harness::Harness<T,S>::poll::h013c9cdfa581b94d\n  12:     0x55ca7c484a83 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h6dc109e015fbac3a\n  13:     0x55ca7c482ff2 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h62616604b1322868\n  14:     0x55ca7c474185 - tokio::runtime::context::runtime::enter_runtime::h83682faf19531b5e\n  15:     0x55ca7c482ac2 - tokio::runtime::scheduler::multi_thread::worker::run::h4799e93eb5290162\n  16:     0x55ca7c4a5b67 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h4dcceed42318e079\n  17:     0x55ca7c48ab83 - tokio::runtime::task::core::Core<T,S>::poll::h36c6717eb8a0fb47\n  18:     0x55ca7c46fe54 - tokio::runtime::task::harness::Harness<T,S>::poll::h933ac520f88e685a\n  19:     0x55ca7c49a396 - tokio::runtime::blocking::pool::Inner::run::h5042773676f2a8a0\n  20:     0x55ca7c4a44a9 - std::sys::backtrace::__rust_begin_short_backtrace::h5e98fc82aff7df04\n  21:     0x55ca7c490641 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h331e27b410d79e81\n  22:     0x55ca7c4dbd9b - std::sys::pal::unix::thread::Thread::new::thread_start::ha07e360225fa3528\n  23:     0x7feb7e090ea7 - start_thread\n  24:     0x7feb7de64adf - clone\n  25:                0x0 - <unknown>\n\"\"\"\n",
  "filename": "/usr/local/cargo/git/checkouts/aptos-indexer-processor-sdk-fbcf846f4b123c78/6eb78b8/aptos-indexer-processors-sdk/sdk/src/server_framework.rs",
  "line_number": 145,
  "threadName": "tokio-runtime-worker",
  "threadId": "ThreadId(127)",
}
```

### Context

Indexer version: `aptos-indexer-processors-v2.1.1`

The transaction exists on chain and is valid:

```
{
  user_transactions(where: {version: {_eq: 2819452713}}) {
    version
    timestamp
  }
}
```
Result:
```
{
  "version": 2819452713,
  "timestamp": "2025-06-03T23:20:46.418432"
}
```

### config.yaml
```
health_check_port: 30005
server_config:
  processor_mode:
    type: default
    initial_starting_version: 0
  processor_config:
    type: token_v2_processor
  db_config:
    type: postgres_config
    connection_string: postgresql://postgres:password@127.0.0.1:5432/indexer
  transaction_stream_config:
    indexer_grpc_data_service_address: https://grpc.mainnet.aptoslabs.com:443
    indexer_grpc_http2_ping_interval_secs: 60
    indexer_grpc_http2_ping_timeout_secs: 10
    auth_token: "< auth_token >"
    request_name_header: token_v2_processor
```
